# Uncomment the next line to define a global platform for your project
# platform :ios, '12.1'

target 'UITableView' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for UITableView

  pod 'RxSwift'
  pod 'RxCocoa'

  target 'UITableViewTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'UITableViewUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
